'use strict';

module.exports = {
	app: {
		title: '18f - OpenFDA Trillion Visualization',
		description: '18f - OpenFDA Trillion Visualization',
		keywords: '18f openFDA trillion ttsi gsa'
	},
	
	port: process.env.PORT || 3000,
	
	thresholds: {lead:0},
	ApiReqIntervalMs:1000,
	  states: {
		  	"US:01": "AL",
		    "US:02": "AK",
		    "US:04": "AZ",
		    "US:05": "AR",
		    "US:06": "CA",
		    "US:08": "CO",
		    "US:09": "CT",
		    "US:10": "DE",
		    "US:11": "DC",
		    "US:12": "FL",
		    "US:13": "GA",
		    "US:15": "HI",
		    "US:16": "ID",
		    "US:17": "IL",
		    "US:18": "IN",
		    "US:19": "IA",
		    "US:20": "KS",
		    "US:21": "KY",
		    "US:22": "LA",
		    "US:23": "ME",
		    "US:24": "MD",
		    "US:25": "MA",
		    "US:26": "MI",
		    "US:27": "MN",
		    "US:28": "MS",
		    "US:29": "MO",
		    "US:30": "MT",
		    "US:31": "NE",
		    "US:32": "NV",
		    "US:33": "NH",
		    "US:34": "NJ",
		    "US:35": "NM",
		    "US:36": "NY",
		    "US:37": "NC",
		    "US:38": "ND",
		    "US:39": "OH",
		    "US:40": "OK",
		    "US:41": "OR",
		    "US:42": "PA",
		    "US:44": "RI",
		    "US:45": "SC",
		    "US:46": "SD",
		    "US:47": "TN",
		    "US:48": "TX",
		    "US:49": "UT",
		    "US:50": "VT",
		    "US:51": "VA",
		    "US:53": "WA",
		    "US:54": "WV",
		    "US:55": "WI",
		    "US:56": "WY"
		}
};
